# Ubuntu: focal
#    ROS: 1 (noetic)
#   CUDA: 11.6.2
#   NVCC: +
FROM nvidia/cuda:11.6.2-base-ubuntu20.04

# Run commands in build phase with bash, allows using `source`
SHELL ["/bin/bash", "-l", "-c"]

# To not be prompted with interactive menus (e.g. geo-zone in apt-get install)
ARG DEBIAN_FRONTEND=noninteractive

# Some basic python libraries, development package (e.g. for building
# bindings), basic software.
RUN apt-get update && apt-get install -y \
    python3-dev python3-matplotlib python3-numpy python3-psutil python3-tk \
    nano vim git curl wget tmux ssh build-essential gcc g++ \
    gdb clang cmake rsync tar bzip2

# Install ROS and xsarm packages. Does not install MATLAB package.
# The script creates a ROS workspace directory at `~/interbotix_ws`.
# Also installs AprilTag and RealSense ROS packages.
COPY docker/xsarm_amd64_install.sh /opt/

#RUN echo "#!/bin/bash\n'$@'" >> /usr/bin/sudo && chmod a+x /usr/bin/sudo
RUN /opt/xsarm_amd64_install.sh -d noetic -n -r
#RUN rm /usr/bin/sudo

# ROS build manager and commons. TODO(aty): revisit.
RUN apt-get install -y python3-catkin-tools python3-osrf-pycommon

# Math/opt libs. Not required now, but necessary for tons of mapping software.
RUN apt-get install -y \
    libeigen3-dev libgoogle-glog-dev \
    libgflags-dev libatlas-base-dev libeigen3-dev \
    libsuitesparse-dev libceres-dev \
    libopenblas-dev libopenexr-dev 

RUN apt-get update && apt-get clean

# Installing micromamba (slim and faster anaconda).
RUN apt-get update \
    && wget -qO-  https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba \
    && touch /root/.bashrc \
    && ./bin/micromamba shell init -s bash -p /opt/conda  \
    && grep -v '[ -z "\$PS1" ] && return' /root/.bashrc  > /opt/conda/bashrc   # this line has been modified \
    && apt-get clean autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log}