import pathlib
import os

### Task parameters
SCRIPT_DIR = pathlib.Path(__file__).parent.absolute()
DEFAULT_DATA_DIR = str(SCRIPT_DIR.parent / "datasets")
DATA_DIR = os.getenv("DATA_DIR", default=DEFAULT_DATA_DIR)
SIM_TASK_CONFIGS = {
    'test_pickup':{
        'dataset_dir': DATA_DIR + '/test_pickup',
        'num_episodes': 100,
        'episode_len': 1000,
        'camera_names': ['cam_high']
    },
    'test_feeding':{
        'dataset_dir': DATA_DIR + '/test_feeding',
        'num_episodes': 150,
        'episode_len': 1300,
        'camera_names': ['cam_high']
    },
}

### Simulation envs fixed constants
DT = 0.02
FPS = 50
#JOINT_NAMES = ["waist", "shoulder", "elbow", "forearm_roll", "wrist_angle", "wrist_rotate"]
#START_ARM_POSE = [0, -0.96, 1.16, 0, -0.3, 0, 0.02239, -0.02239,  0, -0.96, 1.16, 0, -0.3, 0, 0.02239, -0.02239]
JOINT_NAMES = ["waist", "shoulder", "elbow", "wrist_angle", "wrist_rotate"]
START_ARM_POSE = [0, -0.96, 1.21, -0.3, 0.0, 0.31, 0.31]  # calibrated for rx200
SLEEP_ARM_POSE = [0, -1.83, 1.61, 0.61, 0.0]  # calibrated for rx200
ROBOT_MODEL = "rx200"
NUM_JOINTS = len(JOINT_NAMES)

XML_DIR = str(pathlib.Path(__file__).parent.resolve()) + '/assets/' # note: absolute path

# Left finger position limits (qpos[NUM_JOINTS+1]), right_finger = -1 * left_finger
# RX200
MASTER_GRIPPER_POSITION_OPEN = 0.0345
MASTER_GRIPPER_POSITION_CLOSE = 0.015
PUPPET_GRIPPER_POSITION_OPEN = 0.0345
PUPPET_GRIPPER_POSITION_CLOSE = 0.015

# ALOHA
# MASTER_GRIPPER_POSITION_OPEN = 0.02417
# MASTER_GRIPPER_POSITION_CLOSE = 0.01244
# PUPPET_GRIPPER_POSITION_OPEN = 0.05800
# PUPPET_GRIPPER_POSITION_CLOSE = 0.01844

# Gripper joint limits (qpos[NUM_JOINTS])
MASTER_GRIPPER_JOINT_OPEN = 0.997
MASTER_GRIPPER_JOINT_CLOSE = -0.3774
PUPPET_GRIPPER_JOINT_OPEN = 0.997
PUPPET_GRIPPER_JOINT_CLOSE = -0.3774

# ALOHA
# MASTER_GRIPPER_JOINT_OPEN = 0.3083
# MASTER_GRIPPER_JOINT_CLOSE = -0.6842
# PUPPET_GRIPPER_JOINT_OPEN = 1.4910
# PUPPET_GRIPPER_JOINT_CLOSE = -0.6213


############################ Helper functions ############################

MASTER_GRIPPER_POSITION_NORMALIZE_FN = lambda x: (x - MASTER_GRIPPER_POSITION_CLOSE) / (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE)
PUPPET_GRIPPER_POSITION_NORMALIZE_FN = lambda x: (x - PUPPET_GRIPPER_POSITION_CLOSE) / (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE)
MASTER_GRIPPER_POSITION_UNNORMALIZE_FN = lambda x: x * (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE) + MASTER_GRIPPER_POSITION_CLOSE
PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN = lambda x: x * (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE) + PUPPET_GRIPPER_POSITION_CLOSE
MASTER2PUPPET_POSITION_FN = lambda x: PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN(MASTER_GRIPPER_POSITION_NORMALIZE_FN(x))

MASTER_GRIPPER_JOINT_NORMALIZE_FN = lambda x: (x - MASTER_GRIPPER_JOINT_CLOSE) / (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE)
PUPPET_GRIPPER_JOINT_NORMALIZE_FN = lambda x: (x - PUPPET_GRIPPER_JOINT_CLOSE) / (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE)
MASTER_GRIPPER_JOINT_UNNORMALIZE_FN = lambda x: x * (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE) + MASTER_GRIPPER_JOINT_CLOSE
PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN = lambda x: x * (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE) + PUPPET_GRIPPER_JOINT_CLOSE
MASTER2PUPPET_JOINT_FN = lambda x: PUPPET_GRIPPER_JOINT_UNNORMALIZE_FN(MASTER_GRIPPER_JOINT_NORMALIZE_FN(x))

MASTER_GRIPPER_VELOCITY_NORMALIZE_FN = lambda x: x / (MASTER_GRIPPER_POSITION_OPEN - MASTER_GRIPPER_POSITION_CLOSE)
PUPPET_GRIPPER_VELOCITY_NORMALIZE_FN = lambda x: x / (PUPPET_GRIPPER_POSITION_OPEN - PUPPET_GRIPPER_POSITION_CLOSE)

MASTER_POS2JOINT = lambda x: MASTER_GRIPPER_POSITION_NORMALIZE_FN(x) * (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE) + MASTER_GRIPPER_JOINT_CLOSE
MASTER_JOINT2POS = lambda x: MASTER_GRIPPER_POSITION_UNNORMALIZE_FN((x - MASTER_GRIPPER_JOINT_CLOSE) / (MASTER_GRIPPER_JOINT_OPEN - MASTER_GRIPPER_JOINT_CLOSE))
PUPPET_POS2JOINT = lambda x: PUPPET_GRIPPER_POSITION_NORMALIZE_FN(x) * (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE) + PUPPET_GRIPPER_JOINT_CLOSE
PUPPET_JOINT2POS = lambda x: PUPPET_GRIPPER_POSITION_UNNORMALIZE_FN((x - PUPPET_GRIPPER_JOINT_CLOSE) / (PUPPET_GRIPPER_JOINT_OPEN - PUPPET_GRIPPER_JOINT_CLOSE))

MASTER_GRIPPER_JOINT_MID = (MASTER_GRIPPER_JOINT_OPEN + MASTER_GRIPPER_JOINT_CLOSE)/2
