name: assistive_arm_manipulation_jaco_lowdim

task_name: &task_name ArmManipulation
robot_name: &robot_name Jaco
dataset_path: &dataset_path ${task.dataset_path}

obs_dim: 25 # for Jaco
action_dim: 7
keypoint_dim: 0

env_runner:
  _target_: diffusion_policy.env_runner.assistive_lowdim_runner.AssistiveLowdimRunner
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: null
  task_name: *task_name
  robot_name: *robot_name

dataset:
  _target_: diffusion_policy.dataset.assistive_dataset.AssistiveLowdimDataset
  zarr_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.05
  max_train_episodes: null
